services:
  postgres:
    image: postgres:latest@sha256:32ca0af8e77bfb8c6610c488e4691f83f972a3e9e64d3b02facf3ab111ad5500
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  test:
    build: .
    command: env
    links:
      - postgres
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      CYBERSOURCE_MERCHANT_ID:
      CYBERSOURCE_ORG_ID:
      CYBERSOURCE_PROFILE:
      CYBERSOURCE_ACCESS:
      CYBERSOURCE_SECRET:
      CYBERSOURCE_PKCS12_DATA:
      CYBERSOURCE_PKCS12_PASSWORD:
