# Generated by Django 5.2.11 on 2026-02-18 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cybersource", "0009_auto_20190927_0952"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cybersourcereply",
            index=models.Index(
                condition=models.Q(("data", {}), _negated=True),
                fields=["date_created"],
                name="cybersource_reply_scrub_cands",
            ),
        ),
    ]
