# Generated by Django 1.11.9 on 2018-01-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_auto_20160601_1949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Reference"
            ),
        ),
    ]
