# Generated by Django 3.2.16 on 2022-11-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_auto_20210201_1747"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="authorization",
            field=models.ForeignKey(
                blank=True,
                help_text="For capture (debit) transactions, link to the authorization transaction that allowed the capture to take place.",
                limit_choices_to={"txn_type": "Authorise"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captures",
                to="payment.transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("txn_type", "Debit"),
                    ("authorization__isnull", True),
                    _connector="OR",
                ),
                name="only_captures_have_auths",
            ),
        ),
    ]
