# Generated by Django 2.2.1 on 2019-05-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cybersource", "0007_auto_20190515_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cybersourcereply",
            name="reply_type",
            field=models.SmallIntegerField(
                choices=[(1, "Secure Acceptance"), (2, "SOAP API")], default=1
            ),
        ),
    ]
